### PR TITLE
Specify Python 3.7 Runtime for Azure app

### PR DESCRIPTION
**Pull request by tdowrick**
Without a runtime version specified, Python 3.10 is installed.

Not all of the package versions pinned in requirements.txt are compatible with 3.10 and the app launch fails.

Using Python 3.7 as this is the same version as specified in the anaconda environment config.

### CODE REVIEW

**Review by peterhessey — APPROVED** [review]

**Review by ant0nsc — APPROVED** [review]

**Comment by ant0nsc** [comment]
@peterhessey , something's wrong with the actions here, they don't start. Maybe push a dummy commit to trigger again? (/azp run did not have any effect because it's a Github action)

**Comment by ant0nsc** [comment]
... Looking at the workflow again, I'm not sure the trigger conditions are correct. Here's what we have in `hi-ml`:
```
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
```

**Comment by ant0nsc** [comment]
@tdowrick , could you please merge the latest `main` into your branch, so that we can merge this PR?
@peterhessey FYI

**Comment by tdowrick** [comment]
@ant0nsc Done

**Pull request merged**
